### ISSUE TITLE
Checklist for CHS, Jan. 2020

### ISSUE THREAD

**Issue by neelsmith** [homermultitext/hmt-archive#498]
Sequence to complete:

- [x] Review generating a `CiteLibrary` : add scholia-Iliad indexing
- [x] Export library to cex, including automatically inserting version in header file
- [x] Load a library from generated CEX
- [x] Apply a list of objects implementing an MID validator trait
- [x] Loop through all pages in codex models and apply validators
- [x] write corrigenda.md
